/*
company_code, founder Name, Num Lead Man, Num Sen Man, Num man, num employeee
company code asc
*/
SELECT TBL1.A,C.FOUNDER,TBL1.B,TBL1.C,TBL1.D,TBL1.E FROM (
SELECT
    COMPANY_CODE as A,
    COUNT(DISTINCT(LEAD_MANAGER_CODE)) AS B,
    COUNT(DISTINCT(SENIOR_MANAGER_CODE)) AS C,
    COUNT(DISTINCT(MANAGER_CODE)) AS D,
    COUNT(DISTINCT(EMPLOYEE_CODE)) AS E
FROM
    EMPLOYEE
GROUP BY
    A
ORDER BY
    A) as TBL1
LEFT JOIN
    COMPANY C
        ON C.COMPANY_CODE = TBL1.A
ORDER BY
    TBL1.A;